name: medminder
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  package_info_plus: ^4.0.0
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/mainLogo.png
    - assets/loginLogo.png
    - assets/google.png
    - assets/facebook.png
    - assets/wellcome.png
    - assets/pillReminder.png
    - assets/appointmentReminder.png
    - assets/cpr.png
    - assets/choking.png
    - assets/bleeding.png
    - assets/test.png


flutter_native_splash:
  color: "#08007C"
  image: assets/test.png

  android_12:
    color: "#08007C"
    image: assets/test.png