name: medminder
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo2.png

flutter_native_splash:
  color: "#08007C"
  image: assets/logo2.png

  android_12:
    color: "#08007C"
    image: assets/logo2.png