name: medelyra
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  package_info_plus: ^4.0.0

  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0
  
  flutter_local_notifications: 19.5.0
  timezone: 0.10.1
  flutter_timezone: ^4.1.1

  shared_preferences: ^2.5.3
  
  google_maps_flutter: 2.10.1
  geolocator: ^13.0.4
  http: ^1.5.0

  flutter_google_places_sdk: 0.4.2+1
  url_launcher: ^6.3.1
  google_sign_in: 6.2.2

dependency_overrides:
  geolocator_android: 4.6.1  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/mainLogo.png
    - assets/loginLogo.png
    - assets/google.png
    - assets/facebook.png
    - assets/wellcome.png
    - assets/pillReminder.png
    - assets/appointmentReminder.png
    - assets/splash_icon.png


flutter_native_splash:
  color: "#08007C"
  image: assets/splash_icon.png

  android_12:
    color: "#08007C"
    image: assets/splash_icon.png